{
    "result": [
        {
            "nombre": "2014 Cal-Sierra Densifier Densifier",
            "descripcion": 'Opening Size: 18" (Approx.) (Bolt on Lid)\nChamber Size: 38" x 43" (Approx.)\nHorsepower: 150 HP\nDrive: Emerson Drive\nPower Requirement: 480v - 3ph - 60hz\nControl: Emerson Control Panel\nNote: Very Low Usage\n(2) 10 HP Blowers:  Emerson Saftronics Softstarter\n Unitized System with Operator Platform:  Amp Meter',
            "condicion": 0,
            "estadoProducto": null,
            "precioVenta": 34090.90909090909,
            "precio": 30000,
            "categoria": "9",
            "pais": "US",
            "comision": "(12%)",
            "tiempoEntrega": "",
            "ano": 2014,
            "fabricante": "Cal-Sierra",
            "modelo": "Densifier",
            "referencia": "8068944",
            "capacidad": 0,
            "tonelaje": 0,
            "horasOperacion": 0,
            "power": 0,
            "responsable": "SCRAPPING",
            "diametroTornillo": 0,
            "ETI": "8068944",
            "codigoScrapping": "a063fc29",
            "correoScrapping": "kdcapital",
            "linkRef": "https:\/\/www.kdcapital.com\/product\/2014-cal-sierra-densifier\/",
        }
    ],
    "response": true,
    "statusCode": 200,
    "message": "",
    "errors": [],
}
[
    {
        "name": "2014 Cal-Sierra Densifier Densifier",
        "description": 'Opening Size: 18" (Approx.) (Bolt on Lid)\nChamber Size: 38" x 43" (Approx.)\nHorsepower: 150 HP\nDrive: Emerson Drive\nPower Requirement: 480v - 3ph - 60hz\nControl: Emerson Control Panel\nNote: Very Low Usage\n(2) 10 HP Blowers:  Emerson Saftronics Softstarter\n Unitized System with Operator Platform:  Amp Meter',
        "salePrice": 30000.0,
        "creationYear": 2014,
        "factory": "Cal-Sierra",
        "model": "Densifier",
        "reference": "8068944",
        "images": [
            "https://www.kdcapital.com/wp-content/uploads/2020/06/8068944-16.jpg",
            "https://www.kdcapital.com/wp-content/uploads/2020/06/8068944-4.jpg",
            "https://www.kdcapital.com/wp-content/uploads/2020/06/8068944-12.jpg",
            "https://www.kdcapital.com/wp-content/uploads/2020/06/8068944-2.jpg",
            "https://www.kdcapital.com/wp-content/uploads/2020/06/8068944-10.jpg",
            "https://www.kdcapital.com/wp-content/uploads/2020/06/8068944-9.jpg",
            "https://www.kdcapital.com/wp-content/uploads/2020/06/8068944-14.jpg",
            "https://www.kdcapital.com/wp-content/uploads/2020/06/8068944-13.jpg",
            "https://www.kdcapital.com/wp-content/uploads/2020/06/8068944-15.jpg",
            "https://www.kdcapital.com/wp-content/uploads/2020/06/8068944-1.jpg",
            "https://www.kdcapital.com/wp-content/uploads/2020/06/8068944-8.jpg",
            "https://www.kdcapital.com/wp-content/uploads/2020/06/8068944-7.jpg",
            "https://www.kdcapital.com/wp-content/uploads/2020/06/8068944-11.jpg",
            "https://www.kdcapital.com/wp-content/uploads/2020/06/8068944-3.jpg",
        ],
        "condition": "Used",
        "deliveryTime": "",
        "capacity": 0.0,
        "tonnage": 0.0,
        "timeOperation": 0.0,
        "power": 0.0,
        "screwDiameter": 0.0,
        "eti": "8068944",
        "mailScrapping": "kdcapital",
        "category": "Size Reduction / Granulators / Shredders",
        "linkRef": "https://www.kdcapital.com/product/2014-cal-sierra-densifier/",
        "country": "United States",
    }
]

